[package]
name = "physeter"
version = "0.1.0"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
overflow-checks = true
lto = true

[dependencies]
bytes = "0.5.4"
anyhow = "1.0"

[dependencies.tokio]
version = "0.2"
features = ["full"]
